# Generated by Django 2.0.6 on 2018-06-13 05:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('images', '0005_auto_20180606_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tages',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
