# Generated by Django 2.0.6 on 2018-06-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_image_tages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='tages',
            new_name='tags',
        ),
    ]
